application: digital-axon-666
version: 1
runtime: php
api_version: 1

handlers:
# Needed for PHP
- url: /(.+\.php)$
  script: \1

# Needed for static image files
- url: /(.+\.(gif|png|jpg|jpeg))$
  static_files: \1
  upload: .+\.(gif|png|jpg|jpeg)$
  application_readable: true


- url: /assets/css/
  static_dir: assets/css/
  
  
- url: /
  script: index.php  
  
- url: /about
  script: about/index.php
  
- url: /job
  script: job/index.php

- url: /book
  script: book/index.php
  
