application: digital-axon-666
version: 1
runtime: php
api_version: 1

handlers:
# Needed for PHP
#- url: /(.+\.php)$
#  script: \1

# Needed for static image files
- url: /assets/img/
  static_dir: assets/img/

- url: /assets/css/
  static_dir: assets/css/

- url: /assets/cache/
  static_dir: assets/cache/

- url: /
  script: index.php  

- url: /about
  script: about/index.php

- url: /test.php
  script: test.php 

- url: /contact
  script: contact/index.php

- url: /contact/process.php
  script: contact/process.php

- url: /job
  script: resume/index.php

- url: /resume
  script: resume/index.php 

- url: /book
  script: book/index.php

- url: /sitemap
  script: sitemap/index.php


- url: /blog/(.*\.(htm|html|css|js))$
  static_files: wordpress/\1
  upload: wordpress/.*\.(htm|html|css|js)$
  application_readable: true

- url: /blog/(.*\.(ico|jpg|png|gif))$
  static_files: wordpress/\1
  upload: wordpress/.*\.(htm|html|css|js)$
  application_readable: true  

- url: /wp-content/(.*\.(ico|jpg|png|gif))$
  static_files: wordpress/wp-content/\1
  upload: wordpress/wp-content/.*\.(ico|jpg|png|gif)$
  application_readable: true


- url: /blog/wp-admin/(.+)
  script: wordpress/wp-admin/\1
  secure: always

- url: /blog/wp-admin/
  script: wordpress/wp-admin/index.php
  secure: always

- url: /blog/wp-login.php
  script: wordpress/wp-login.php
  secure: always

- url: /wp-cron.php
  script: wordpress/wp-cron.php
  login: admin

- url: /xmlrpc.php
  script: wordpress/xmlrpc.php

- url: /wp-(.+).php
  script: wordpress/wp-\1.php

- url: /(.+)?/?
  script: wordpress/index.php
