application: arctic-marking-865
module: default
version: 1
api_version: 1
runtime: php55
threadsafe: yes

default_expiration: "30d"

skip_files:
- ^(.*/)?.*\.scss$
- ^(.*/)?.*\.scssc$
- ^(.*/)?.*\.css.map$
- ^(.*/)?.*\.sql$
- ^(.*/)?.*\.git
- ^(.*/)?.*\.DS_Store



handlers:
# Needed for PHP
#- url: /(.+\.php)$
#  script: \1




# Needed for static image files
- url: /assets/
  static_dir: assets/
  expiration: "30d"
  http_headers:
    Vary: Accept-Encoding

- url: /
  script: index.php


- url: /(.+\.php)$
  script: \1 

- url: /about/?
  script: about/index.php

- url: /test.php
  script: test.php 

- url: /contact/?
  script: contact/index.php

- url: /contact/process.php
  script: contact/process.php

- url: /job/?
  script: resume/index.php

- url: /resume/?
  script: resume/index.php 

- url: /search/?
  script: search/index.php   

- url: /book/?
  script: book/index.php

- url: /sitemap/?
  script: sitemap/index.php

- url: /tests/(.+).php
  script: tests/\1.php

- url: /error/(.+).php
  script: error/\1.php  

- url: /max/2013/practicalcss/preso/
  static_files: max/2013/practicalcss/preso/index.html
  upload: max/2013/practicalcss/preso/index.html

- url: /max/2013/programmingcss/preso/
  static_files: max/2013/programmingcss/preso/index.html
  upload: max/2013/programmingcss/preso/index.html  

- url: /max/
  static_dir: max/
  expiration: "30d"
  http_headers:
    Vary: Accept-Encoding 

- url: /presos/animate_reveal/
  static_files: presos/animate_reveal/index.html
  upload: /presos/animate_reveal/index.html

- url: /presos/
  static_dir: presos/
  expiration: "30d"
  http_headers:
    Vary: Accept-Encoding      



  # index files
- url: /presos/animate_reveal
  upload: presos/animate_reveal/
  static_files: presos/animate_reveal/index.html



- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico   
  expiration: "180d" 

- url: /.*
  script: error/error404.php   



